### ISSUE TITLE
Continue running tests even if previous unit tests failed

### ISSUE THREAD

**Issue by fengyuentau** [opencv/ci-gha-workflow#7]
I propose to continue running tests when build completes but previous unit tests fail. You can see from [this log](https://github.com/opencv/ci-gha-workflow/runs/6666090248?check_suite_focus=true) that GitHub Actions workflow stops once there is an error. However, for a workflow which completes building, stopping at one possible failed unit test is too inefficient.

An implementation to this feature can be as follows:
```yaml
jobs:
  BuildAndTest:
    steps:
        # ...
        - name: Build OpenCV
           id: build-opencv # used as reference below
           run: #...
        # ...
        - name: Accuracy:core
          if: ${{ always() && steps.build-opencv.outcome == 'success' }}
          run: #...
```

This should work and show "failed" in overall page if one test fails.

What do you think? @alalek @asenyaev @asmorkalov 

Reference:
- https://stackoverflow.com/a/71434730/6769366
- https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
